###
GET http://localhost:3800/api/clientes/60be3f06af99a4365c7265f5
###
GET http://localhost:3800/api/clientes
Content-Type: application/json


###
POST http://localhost:3800/api/clientes
Content-Type: application/json

{
    "cedula":"1234567800",
    "nombre":"Alia",
    "apellido":"Alcivar",
    "mail":"no se"

}
###
POST http://localhost:3800/api/registro
Content-Type: application/json

{
    "nombre":"Lorena",
    "email":"doum@hotmail.com",
    "clave":"12345"
}

###
POST http://localhost:3800/api/login
Content-Type: application/json

{
    "email":"doum@hotmail.com",
    "clave":"12345"
}

###
GET  http://localhost:3800/api/ver
Content-Type: application/json
Authorization: Beeres hbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MTAyYzQzODMxMjQ2MjMyZDg1NjhmZmMiLCJpYXQiOjE2Mjc1NzE0OTN9.O0UmoFe7sHyLG-rdXbMFjB9-4rMlzY7HJh2rK3XmVgs


###
PUT http://localhost:3800/api/clientes/60be3f06af99a4365c7265f5
Content-Type: application/json

{
    "nombre":"MARIA DOLORES",
    "apellido":"LOLEZ"
}

###
DELETE http://localhost:3800/api/clientes/60be3f06af99a4365c7265f5









